### ISSUE TITLE
can we make this work with --no-home as well?

### ISSUE THREAD

**Issue by kkmann** [kkmann/jupyter-singularity-demo#2]
@vsoch thanks for your help!
I am not entirely happy yet since I still need to bind the user home when executing singularity. I tried to use the `--no-home` option. The problem is that when executing singularity from a subdirectory of my user home, I can bind `$PWD` just fine but get an access denied error as soon as I try to access it. I had hoped that it was possible to completely ignore the user home and only bind the working directory (even if it is a subdirectory of the user home).

**Comment by vsoch** [comment]
why not create another artificial user home, and bind that instead? I'm cloning the repo again now, I'll give it a try and update you if it works.

**Comment by vsoch** [comment]
Hey @kkmann if you don't want to bind the user home, try this:

```bash
#!/usr/bin/env bash

set -e

mkdir -p .jupyter
mkdir -p .home
touch .home/test.txt

singularity exec \
  --bind $PWD/.jupyter:/run/user \
  --home $PWD/.home \
  container.sif \
  jupyter notebook \
  --ip=127.0.0.1 --no-browser
```
To test, we can actually do:

```bash
#!/usr/bin/env bash

set -e

mkdir -p .jupyter
mkdir -p home
touch home/test.txt

singularity shell \
  --bind $PWD/.jupyter:/run/user \
  --home $PWD/home \
  container.sif
```

Since home is inside tmp (already bound) that's where it's shown to be:

```bash
Singularity container.sif:/tmp/jupyter-singularity-demo> echo $HOME
/tmp/jupyter-singularity-demo/home
Singularity container.sif:/tmp/jupyter-singularity-demo> ls $HOME
test.txt
Singularity container.sif:/tmp/jupyter-singularity-demo> 
```
You can put it somewhere else (not already bound) too:

```bash
$ mkdir -p /home/vanessa/Desktop/another-home
$ touch /home/vanessa/Desktop/another-home/pancakes
$ singularity shell   --bind $PWD/.jupyter:/run/user   --home /home/vanessa/Desktop/another-home   container.sif
Singularity container.sif:/tmp/jupyter-singularity-demo> echo $HOME
/home/vanessa/Desktop/another-home
Singularity container.sif:/tmp/jupyter-singularity-demo> ls /home
rstudio  vanessa
Singularity container.sif:/tmp/jupyter-singularity-demo> ls /home/vanessa/Desktop/another-home/
pancakes
```
Notice how the full path is there, however the single "another-home" folder is the only content (the rest of my home is hidden).

Is that what you are looking to do?

**Comment by kkmann** [comment]
:+1: yes, I guess for the kind of application that I have in mind it is safer to redirect home completely.
